{% set name = "requests-pelican" %}
{% set version = "0.2.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/requests_pelican-{{ version }}.tar.gz
  sha256: b1893cd78d0c8478555662bf3102ee722548cb4cae05945911775a2d0677e273

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - setuptools >=70.0
    - setuptools-scm >=3.4.3
    - wheel
    - pip
  run:
    - python >={{ python_min }}
    - requests

test:
  requires:
    - pip
    - pytest >=3.9.1
    - pytest-remotedata
    - python {{ python_min }}
    - requests-mock
    - requests-scitokens
  commands:
    - python3 -m pip check
    - python3 -m pip show requests-pelican
    - python3 -m pytest --pyargs -ra --remote-data=none -v requests_pelican

about:
  summary: A requests addon for Pelican data federations
  dev_url: https://git.ligo.org/computing/software/requests-pelican.git
  doc_url: https://requests-pelican.readthedocs.io
  home: https://git.ligo.org/computing/software/requests-pelican
  license: MIT
  license_file: LICENSE
  description: |
    This project provides [`requests`](https://github.com/psf/requests) addons
    to support HTTP requests to a [Pelican Federation](https://pelicanplatform.org/).

    The main component is a new `PelicanAdapter` class that handles translating
    Pelican URIs into HTTP URLs to enable standard `GET` requests, including
    looping over Pelican caches.

    This project also provides wrappers around `requests.get` (and friends) and
    `requests.Session` to simplify configuring support for Pelican URIs.

extra:
  recipe-maintainers:
    - duncanmmacleod
